<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        DB::table(table: 'modules')->insert(values: [
            [
                'id'        => 1,
                'title'     => 'What is Offensive Security?',
                'description' => "This is the core of 'Offensive Security.' It involves breaking into computer systems, exploiting software bugs, and finding loopholes in applications to gain unauthorized access. The goal is to understand hacker tactics and enhance our system defences.",
                'link_content' => 'https://www.ibm.com/topics/offensive-security',
                'course_id' => 1,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 2,
                'title'     => 'Hacking your first machine',
                'description' => "You will be guided through hacking your first website in a legal and safe environment.",
                'link_content' => 'https://tryhackme.com/r/room/offensivesecurityintro',
                'course_id' => 2,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 3,
                'title'     => 'Careers in cyber security',
                'description' => "This is the core of 'Offensive Security.' It involves breaking into computer systems, exploiting software bugs, and finding loopholes in applications to gain unauthorized access. The goal is to understand hacker tactics and enhance our system defences.",
                'link_content' => 'https://www.coursera.org/articles/cybersecurity-jobs',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 4,
                'title'     => 'Introduction to Defensive Security',
                'description' => "Defensive cyber security focuses on building and maintaining resilient systems that prevent, detect, and respond to threats primarily after an incident occurs.",
                'link_content' => 'https://www.cyberacademy.id/blog/mengenal-defensive-security',
                'course_id' => 2,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 5,
                'title'     => 'Areas of Defensive Security',
                'description' => "Security Operations Center (SOC), where cover Threat Intelligence.",
                'link_content' => 'https://secureguardservices.com/blog/what-are-the-4-levels-of-security/',
                'course_id' => 2,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 6,
                'title'     => 'Practical Example of Defensive Security',
                'description' => "Let us pretend you are a Security Operations Center (SOC) analyst responsible for protecting a bank. ",
                'link_content' => 'https://www.ibm.com/topics/security-operations-center',
                'course_id' => 2,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 7,
                'title'     => 'Practical Example of Defensive Security',
                'description' => "Let us pretend you are a Security Operations Center (SOC) analyst responsible for protecting a bank. ",
                'link_content' => 'https://www.ibm.com/topics/security-operations-center',
                'course_id' => 2,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 8,
                'title'     => 'Security Analyst',
                'description' => "Security analysts are integral to constructing security measures across organisations to protect the company from attacks.",
                'link_content' => 'https://cybersn.com/role/security-analyst/',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 9,
                'title'     => 'Security Engineer',
                'description' => "Security engineers develop and implement security solutions using threats and vulnerability data - often sourced from members of the security workforce.",
                'link_content' => 'https://uk.indeed.com/career-advice/finding-a-job/what-does-security-engineer-do',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 10,
                'title'     => 'Incident Responder',
                'description' => "Incident responders respond productively and efficiently to security breaches. Responsibilities include creating plans, policies, and protocols for organisations to enact during and following incidents.",
                'link_content' => 'https://www.crowdstrike.com/en-us/cybersecurity-101/next-gen-siem/incident-responder/',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 11,
                'title'     => 'Digital Forensics Examiner',
                'description' => "If you are working as part of a law-enforcement department, you would be focused on collecting and analysing evidence to help solve crimes: charging the guilty and exonerating the innocent.",
                'link_content' => 'https://fbijobs.gov/sites/default/files/2023-04/career_digitalforensicexaminer.pdf',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 12,
                'title'     => 'Malware Analyst',
                'description' => "A malware analyst's work involves analysing suspicious programs, discovering what they do and writing reports about their findings.",
                'link_content' => 'https://online.utulsa.edu/blog/malware-analyst-career-overview/',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 13,
                'title'     => 'Penetration Tester',
                'description' => "A penetration tester's job role is to test the security of the systems and software within a company - this is achieved through attempts to uncover flaws and vulnerabilities through systemised hacking.",
                'link_content' => 'https://www.blackduck.com/glossary/what-is-penetration-testing.html',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 14,
                'title'     => 'Red teamer',
                'description' => "Red teamers share similarities to penetration testers, with a more targeted job role.",
                'link_content' => 'https://www.zimperium.com/glossary/red-teamer/',
                'course_id' => 3,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 15,
                'title'     => 'What is Networking?',
                'description' => "Networks come in all shapes and sizes, which is something that we will also come on to discuss throughout this module.",
                'link_content' => 'https://www.careereducation.columbia.edu/resources/what-networking-and-why-do-you-need-do-it',
                'course_id' => 4,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 16,
                'title'     => 'What is Internet?',
                'description' => "The Internet is made up of many small networks all joined together.",
                'link_content' => 'https://www.britannica.com/technology/Internet',
                'course_id' => 4,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 17,
                'title'     => 'Identifying Devices on a Network',
                'description' => "To communicate and maintain order, devices must be both identifying and identifiable on a network.",
                'link_content' => 'https://www.solarwinds.com/resources/it-glossary/network-device-identification',
                'course_id' => 4,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 18,
                'title'     => 'What is LAN?',
                'description' => "Define a Local Area Network, its scope, and how it connects devices in a small geographical area.",
                'link_content' => 'https://www.cisco.com/c/en/us/products/switches/what-is-a-lan-local-area-network.html',
                'course_id' => 5,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 19,
                'title'     => 'LAN Components',
                'description' => "Learn about LAN components, including switches, routers, network cables, and end devices.",
                'link_content' => 'https://www.geeksforgeeks.org/physical-components-of-computer-network/',
                'course_id' => 5,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 20,
                'title'     => 'LAN Topologies',
                'description' => "Understand various LAN topologies like star, bus, ring, and mesh, and their advantages and disadvantages.",
                'link_content' => 'https://cdn.ttgtmedia.com/searchNetworking/Downloads/NetConsultantsch2.pdf',
                'course_id' => 5,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 21,
                'title'     => 'What is OSI Model?',
                'description' => "Learn the seven layers of the OSI Model and their respective roles in networking.",
                'link_content' => 'https://www.geeksforgeeks.org/open-systems-interconnection-model-osi/',
                'course_id' => 6,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 22,
                'title'     => 'OSI Model vs TCP/IP Model',
                'description' => "Compare the OSI Model with the TCP/IP model, highlighting their differences and similarities.",
                'link_content' => 'https://www.fortinet.com/resources/cyberglossary/tcp-ip-model-vs-osi-model',
                'course_id' => 6,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 23,
                'title'     => 'Understanding Packets',
                'description' => "Learn what packets are, how data is segmented, and their structure in a network.",
                'link_content' => 'https://www.cloudflare.com/learning/network-layer/what-is-a-packet/',
                'course_id' => 7,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 24,
                'title'     => 'Frames in Networking',
                'description' => "Discover how frames work and their role in network communication.",
                'link_content' => 'https://www.ituonline.com/tech-definitions/what-is-a-frame-in-networking/',
                'course_id' => 7,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 25,
                'title'     => 'Packets vs Frames',
                'description' => "Understand the difference between packets and frames, including where each operates in the OSI model.",
                'link_content' => 'https://www.pynetlabs.com/what-is-the-difference-between-packet-and-frame/',
                'course_id' => 7,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 26,
                'title'     => 'Subnetting',
                'description' => "Learn how subnetting divides a network into smaller, more manageable segments.",
                'link_content' => 'https://www.9tut.com/subnetting-tutorial',
                'course_id' => 8,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 27,
                'title'     => 'Introduction to DNS',
                'description' => "Explore what DNS is, why it's essential, and its role in the internet's functioning.",
                'link_content' => 'https://www.cloudflare.com/learning/dns/what-is-dns/',
                'course_id' => 9,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 28,
                'title'     => 'DNS Records',
                'description' => "Learn about DNS record types and their use cases.",
                'link_content' => 'https://www.site24x7.com/learn/dns-record-types.html',
                'course_id' => 9,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 29,
                'title'     => 'HTTP Basics',
                'description' => "Understand HTTP methods, status codes, and the request-response cycle.",
                'link_content' => 'https://www.w3schools.com/whatis/whatis_http.asp',
                'course_id' => 10,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 30,
                'title'     => 'HTTP Headers',
                'description' => "Analyze HTTP headers, their categories, and how they control communication between clients and servers.",
                'link_content' => 'https://www.geeksforgeeks.org/http-headers/',
                'course_id' => 10,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 31,
                'title'     => 'HTTPS and Encryption',
                'description' => "Learn about HTTPS, how SSL/TLS encrypts communication, and how certificates work.",
                'link_content' => 'https://www.digicert.com/what-is-ssl-tls-and-https',
                'course_id' => 10,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 32,
                'title'     => 'Web Servers and Hosting',
                'description' => "Learn about web servers like Apache and Nginx, and how hosting services operate.",
                'link_content' => 'https://www.geeksforgeeks.org/difference-between-web-server-and-web-host/',
                'course_id' => 11,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 33,
                'title'     => 'Frontend vs Backend',
                'description' => "Differentiate between frontend and backend technologies and their roles in website development.",
                'link_content' => 'https://www.geeksforgeeks.org/frontend-vs-backend/',
                'course_id' => 12,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 34,
                'title'     => 'Setting Up a Website',
                'description' => "Use DNS settings, hosting, and HTTP configurations to create and deploy a basic website.",
                'link_content' => 'https://www.wix.com/blog/how-to-build-website-from-scratch-guide',
                'course_id' => 12,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 35,
                'title'     => 'What is Linux?',
                'description' => "Explore Linux's history, distributions, and the role it plays in modern computing.",
                'link_content' => 'https://www.linux.com/what-is-linux/',
                'course_id' => 13,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 36,
                'title'     => 'Basic Linux Commands',
                'description' => "Learn essential Linux commands to navigate the file system.",
                'link_content' => 'https://www.geeksforgeeks.org/basic-linux-commands/',
                'course_id' => 13,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 37,
                'title'     => 'Linux Permissions and Ownership',
                'description' => "Discover the basics of file permissions, ownership, and how to modify them.",
                'link_content' => 'https://linuxhandbook.com/linux-file-permissions/',
                'course_id' => 13,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 38,
                'title'     => 'File and Text Manipulation',
                'description' => "Discover commonly used tools for advanced text processing.",
                'link_content' => 'https://everythingdevops.dev/linux-text-processing-commands/',
                'course_id' => 14,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 39,
                'title'     => 'Basic Networking in Linux',
                'description' => "Explore Linux networking commands.",
                'link_content' => 'https://www.geeksforgeeks.org/linux-network-commands-cheat-sheet/',
                'course_id' => 14,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 40,
                'title'     => 'Virtualization in Linux',
                'description' => "Explore virtualization concepts and tools.",
                'link_content' => 'https://www.scaler.com/topics/linux-virtualization/',
                'course_id' => 15,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 41,
                'title'     => 'Windows OS Overview',
                'description' => "Understand the history, versions, and features of the Windows operating system.",
                'link_content' => 'https://it.telkomuniversity.ac.id/en/windows-operating-system/',
                'course_id' => 16,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 42,
                'title'     => 'Windows File System',
                'description' => "Learn about NTFS and FAT32, and how to manage files and folders in Windows.",
                'link_content' => 'https://learn.microsoft.com/en-us/troubleshoot/windows-client/backup-and-storage/fat-hpfs-and-ntfs-file-systems',
                'course_id' => 16,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 43,
                'title'     => 'User Accounts and Permissions',
                'description' => "Manage user accounts and set permissions in Windows.",
                'link_content' => 'https://learn.microsoft.com/en-us/windows/security/identity-protection/access-control/access-control',
                'course_id' => 16,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 44,
                'title'     => 'Windows Networking Basics',
                'description' => "Set up and troubleshoot basic networking on Windows, including Wi-Fi and Ethernet.",
                'link_content' => 'https://learn.microsoft.com/en-us/windows/win32/wnet/windows-networking-wnet-',
                'course_id' => 17,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 45,
                'title'     => 'Windows Command Line Basics',
                'description' => "Learn key commands in the Windows Command Prompt (CMD).",
                'link_content' => 'https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands',
                'course_id' => 17,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 46,
                'title'     => 'Introduction to PowerShell',
                'description' => "Explore the basics of Windows PowerShell for advanced task automation.",
                'link_content' => 'https://learn.microsoft.com/id-id/powershell/scripting/windows-powershell/starting-windows-powershell',
                'course_id' => 17,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 47,
                'title'     => 'Windows Security Features',
                'description' => "Learn about Windows Defender, firewalls, and user authentication methods.",
                'link_content' => 'https://support.microsoft.com/en-us/windows/stay-protected-with-windows-security-2ae0363d-0ada-c064-8b56-6a39afb6a963',
                'course_id' => 18,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
            [
                'id'        => 48,
                'title'     => 'Windows Registry Basics',
                'description' => "Understand the Windows Registry, its purpose, and how to safely modify it.",
                'link_content' => 'https://www.lifewire.com/windows-registry-2625992',
                'course_id' => 18,
                'created_at'=> Carbon::now(),
                'updated_at'=> Carbon::now(),
            ],
        ]);
    }
}
